title: [Badrul's GitHub Repository]
description: ["Where computing, maths, and business hang out"]
theme: jekyll-theme-tactile
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
markdown: kramdown
mathjax: trie
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: roug
