title: ["ReddSpark's Data Science & ML Page"]
description: ["Notes, Projects, and Resources"]
theme: jekyll-theme-tactile
highlighter: rouge
markdown: kramdown
future: true
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: roug
theme: jekyll-theme-tactile
